import assert from 'node:assert/strict';
import fs from 'node:fs';
import {homeCinema,homeDiagrams} from './momm-site-home.mjs';
import {bindHomePlayers} from '../docs/momm/home-player.mjs';
const tour=JSON.parse(fs.readFileSync(new URL('../docs/momm/tour.json',import.meta.url)));
const data=JSON.parse(fs.readFileSync(new URL('../docs/evidence/momm-evidence.json',import.meta.url)));
const stats=JSON.parse(fs.readFileSync(new URL('../docs/momm/data/public-stats.json',import.meta.url)));
const cinema=homeCinema(tour,tour.version);
assert.equal((cinema.match(/<video /g)||[]).length,1);
assert.equal((cinema.match(/class="chapter-frame"/g)||[]).length,4);
for(const id of ['install','setup','ledger','quality'])assert(cinema.includes(`watch/overview.html?t=${tour.chapters.find(c=>c.id===id).start}`));
assert(cinema.includes('same introduction, not four separate films'));
assert(cinema.includes('synthetic Dom narration at 1.5×'));
assert(cinema.includes('Video narration: <a href="https://www.promptus.ai/"><strong>Built with Promptus</strong> · promptus.ai ↗</a>'));
assert(!cinema.includes('autoplay'));
assert(!cinema.includes('replacement video will appear'));
assert(!cinema.includes('127.0.0.1'));
const pending=homeCinema({...tour,status:'pending_voice_acceptance'},tour.version);
assert(!pending.includes('<video'));assert(!pending.includes('coming soon'));assert(pending.includes('start.html'));
assert(homeCinema(tour,'9.9.9').includes('Current release: 9.9.9'));
assert.throws(()=>homeCinema({...tour,chapters:[]},tour.version),/chapter missing/);
const diagrams=homeDiagrams(data,stats,tour.version);
assert.equal((diagrams.match(/<figure /g)||[]).length,7);
assert.equal((diagrams.match(/<details /g)||[]).length,7);
assert(diagrams.includes('id="home-stacking-title"'));
assert(diagrams.includes('aria-labelledby="home-stacking-title home-stacking-desc"'));
assert(!diagrams.includes('following table'));
assert(diagrams.includes('10% shared-blind-spot floor'));
const home=fs.readFileSync(new URL('../docs/momm/index.html',import.meta.url),'utf8');
assert.equal((home.match(/id="walkthrough"/g)||[]).length,1);
assert.equal((home.match(/MOMM HOME COMPANIONS/g)||[]).length,1);
assert(home.indexOf('id="walkthrough"')<home.indexOf('id="architecture-library"'));
assert.equal((home.match(/<figure /g)||[]).length,7);
assert(!home.includes('private-draft-films'));
assert(!home.includes('The written walkthrough below is ready.'));
assert.equal((home.match(/<video /g)||[]).length,3);
assert.equal((home.match(/class="film-start"/g)||[]).length,3);
assert(home.includes('home-player.mjs'));
assert(!home.includes('films/ledger/'));
const films=JSON.parse(fs.readFileSync(new URL('../docs/momm/films.json',import.meta.url)));
assert.equal((homeCinema(tour,tour.version,films).match(/<video /g)||[]).length,3);
assert.equal((homeCinema(tour,tour.version,films.map(f=>({...f,status:'pending'}))).match(/<video /g)||[]).length,1);
const listeners={},links=[{dataset:{play:'home-film',time:'113.14'},addEventListener(k,fn){this.click=fn;}},{dataset:{play:'home-setup'},addEventListener(k,fn){this.click=fn;}}];
const makeVideo=id=>({id,readyState:1,duration:220,currentTime:0,paused:true,addEventListener(k,fn){listeners[id+':'+k]=fn;},focus(){},scrollIntoView(){},getAttribute(){return id;},play(){this.paused=false;listeners[id+':play']();return Promise.resolve();},pause(){this.paused=true;}});
const main=makeVideo('home-film'),setup=makeVideo('home-setup'),status={},overlay={hidden:false};
const doc={querySelectorAll(q){return q==='[data-play]'?links:[main,setup];},querySelector(){return overlay;},getElementById(id){return {'home-film':main,'home-setup':setup,'home-player-status':status}[id];}};
bindHomePlayers(doc);let prevented=false;const click={button:0,preventDefault(){prevented=true;}};
await links[0].click({...click,ctrlKey:true});assert(!prevented,'modified clicks retain fallback navigation');
await links[0].click(click);assert(prevented);assert.equal(main.currentTime,113.14);assert.equal(main.paused,false);assert(overlay.hidden);
await links[1].click(click);assert(main.paused);assert(!setup.paused,'one film at a time');
links[0].dataset.time='9999';await links[0].click(click);assert.equal(main.currentTime,219.9);
main.readyState=0;links[0].dataset.time='34.08';await links[0].click(click);listeners['home-film:loadedmetadata']();assert.equal(main.currentTime,34.08);
main.play=()=>Promise.reject(Error('blocked'));await links[0].click(click);assert(status.textContent.includes('did not start'));
main.readyState=1;main.play=()=>{main.currentTime=0;return Promise.resolve();};links[0].dataset.time='189.3';await links[0].click(click);assert.equal(main.currentTime,189.3,'reapply chapter seek if initial media playback resets it');
console.log('Homepage: three approved films, in-page playable thumbnails, exact seeking, one audio stream, fallback links, seven diagrams and held-media exclusion pass.');
