import fs from'node:fs';import path from'node:path';import{fileURLToPath,pathToFileURL}from'node:url';import assert from'node:assert/strict';import vm from'node:vm';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..'),repo=root;
const search=await import('./momm-site-search.mjs'),video=await import('./momm-site-videos.mjs');
const tour=JSON.parse(fs.readFileSync(path.join(root,'docs/momm/tour.json'))),script=fs.readFileSync(path.join(root,'docs/momm/watch.js'),'utf8');
const fixture=()=>({'docs/momm/releases/9.9.9.html':'<html><head><title>x</title></head><body><main id="main">Original content</main></body></html>'});
const catalogue=[{version:'9.9.9',kind:'release',summary:"cost $& and $' here",source_url:'https://github.com/marroccofella/skills'}];
const html=t=>video.watchOutputs(t,t.version,repo)['docs/momm/watch/overview.html'];
function runtime(){const listeners={},v={duration:220,currentTime:113.14,readyState:0,scrolled:false,scrollIntoView(){this.scrolled=true;},addEventListener(){},play(){return Promise.resolve();}},status={},field={parentElement:{hidden:true},focus(){this.focused=true;},select(){this.selected=true;}},buttons={};for(const id of ['copy-video','share-video'])buttons[id]={dataset:{title:'Title',text:'Text'},addEventListener(k,fn){listeners[id]=fn;}};const a={dataset:{seek:'113.14'},getAttribute(){return'?t=113.14';},addEventListener(k,fn){listeners.anchor=fn;}};const context={URL,document:{getElementById(id){return id==='watch-video'?v:id==='share-status'?status:id==='share-link'?field:buttons[id];},querySelector(){return{href:'https://marroccofella.github.io/skills/momm/watch/overview.html'};},querySelectorAll(){return[a];}},location:{href:'https://marroccofella.github.io/skills/momm/watch/overview.html'},history:{pushState(){}},window:{addEventListener(){}},navigator:{clipboard:{writeText(){return Promise.reject(Error('blocked'));}}}};vm.createContext(context);vm.runInContext(script,context);return{context,listeners,v,status,field,buttons};}
const checks={
 'replace-dollar-pattern-injection':()=>{const f=fixture();search.enhanceSearch(f,{version:'9.9.9',catalogue});const graph=JSON.parse(f[Object.keys(f)[0]].match(/ld\+json">([\s\S]*?)<\/script>/)[1]);assert(graph['@graph'][0].description.includes("$& and $'"));},
 'share-text-unvalidated-title':()=>{const t={...tour};delete t.title;assert.throws(()=>video.validateTour(t,repo),/title/i);},
 'share-url-floors-chapter-time':()=>{const r=runtime();assert.equal(new URL(vm.runInContext('shareUrl()',r.context)).searchParams.get('t'),'113.14');},
 'videoobject-description-not-visible':()=>assert(html(tour).split('<body>')[1].includes(tour.description)),
 'caption-url-as-text':()=>{const graph=JSON.parse(html(tour).match(/ld\+json">([\s\S]*?)<\/script>/)[1]);assert.equal(graph['@graph'].find(n=>n['@type']==='VideoObject').caption.encodingFormat,'text/vtt');},
 'published-date-not-w3c':()=>assert.throws(()=>video.validateTour({...tour,published_date:'September 13, 2026'},repo)),
 'canonical-index-suffix-overmatch':()=>{assert.equal(search.canonicalUrl('docs/momm/reindex.html'),search.SITE+'momm/reindex.html');assert.throws(()=>search.canonicalUrl('docs/./x.html'));},
 'transcript-seek-offscreen':()=>{const r=runtime();r.listeners.anchor({button:0,preventDefault(){}});assert(r.v.scrolled);},
 'chapter-id-uniqueness-unchecked':()=>assert.throws(()=>video.validateTour({...tour,chapters:tour.chapters.map((c,i)=>i===1?{...c,id:tour.chapters[0].id}:c)},repo)),
 'hardcoded-runtime-copy':()=>{const t={...tour,duration_seconds:210,chapters:[{...tour.chapters[0],start:0,end:210}]};assert(html(t).includes('3 minutes 30 seconds'));assert(!html(t).includes('3 minutes 40 seconds'));},
 'breadcrumb-idempotency':()=>{const f=fixture();search.enhanceSearch(f,{version:'9.9.9',catalogue:[{...catalogue[0],summary:'safe'}]});const before=f[Object.keys(f)[0]];search.enhanceSearch(f,{version:'9.9.9',catalogue:[{...catalogue[0],summary:'safe'}]});assert.equal(f[Object.keys(f)[0]],before);},
 'head-only-rewrite':()=>{const f=fixture();f[Object.keys(f)[0]]=f[Object.keys(f)[0]].replace('</main>','<meta name="description" content="body-data"></main>');search.enhanceSearch(f,{version:'9.9.9',catalogue:[{...catalogue[0],summary:'safe'}]});assert(f[Object.keys(f)[0]].includes('content="body-data"'));},
 'null-media-hashes':()=>assert.throws(()=>video.validateTour({...tour,media_hashes:null},repo),/media hashes/i),
 'share-failure-fallback':async()=>{const r=runtime();await r.listeners['copy-video']();await new Promise(r=>setTimeout(r,0));assert.equal(r.field.value,'https://marroccofella.github.io/skills/momm/watch/overview.html?t=113.14');assert(r.field.selected);r.context.navigator.share=()=>Promise.reject({name:'AbortError'});await r.listeners['share-video']({currentTarget:r.buttons['share-video']});r.context.navigator.share=()=>Promise.reject({name:'NotAllowedError'});await r.listeners['share-video']({currentTarget:r.buttons['share-video']});assert(r.field.selected);},
 'duration-signal-mismatch':()=>{const out=video.watchOutputs(tour,tour.version,repo),graph=JSON.parse(out['docs/momm/watch/overview.html'].match(/ld\+json">([\s\S]*?)<\/script>/)[1]),seconds=Number(graph['@graph'].find(n=>n['@type']==='VideoObject').duration.match(/PT([\d.]+)S/)[1]),integer=Number(out['docs/video-sitemap.xml'].match(/<video:duration>(\d+)<\/video:duration>/)[1]);assert(Math.abs(seconds-integer)<=.5);console.log('Both represent the same measured duration; sitemap seconds are intentionally integer-quantized. Google video-sitemaps reference permits only integer duration.');},
 'og-preview-incomplete':()=>{assert(html(tour).includes('og:title'));assert(html(tour).includes('og:description'));assert(html(tour).includes('thumbnailUrl'));assert(html(tour).includes('og:image'));}
};
const keys=Object.keys(checks);let failed=0;
for(const key of keys){try{await checks[key]();console.log('PASS '+key);}catch(e){failed++;console.log('FAIL '+key+' '+e.message);}}
process.exitCode=failed?1:0;
